### ISSUE TITLE
Todos os Elementos <a> ficam Azul em Login.scss

### ISSUE THREAD

**Issue by iagoOliv** [Julio-Caio/CyCad#5]
```scss
&__wrapper {
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: .8rem;

    & div,
    & a {
        width: 100%;
    }

    & a:hover {
        color: #2563eb;
    }
```
em  `Login.scss`
